(()=>{
const ko=()=>document.documentElement.lang==='ko';
const tabs=[...document.querySelectorAll('[data-category]')],list=document.querySelector('#video-list');let category=0;
function renderVideos(){list.replaceChildren();list.setAttribute('aria-labelledby',`category-${category}`);tabs.forEach((tab,i)=>{tab.setAttribute('aria-selected',String(i===category));tab.setAttribute('aria-pressed',String(i===category));tab.tabIndex=i===category?0:-1});window.lessonVideos.filter(v=>v.category===category).forEach(v=>{const article=document.createElement('article');article.className='lesson-video-card';const link=document.createElement('a');link.href=`https://www.youtube.com/watch?v=${encodeURIComponent(v.id)}`;link.target='_blank';link.rel='noopener';link.className='lesson-video-thumbnail';link.setAttribute('aria-label',ko()?v.koreanTitle:v.englishTitle);const image=document.createElement('img');image.src=v.thumbnail;image.alt='';image.loading='lazy';image.width=200;image.height=180;link.append(image);const content=document.createElement('div');content.className='lesson-video-details';const heading=document.createElement('div');heading.className='lesson-video-heading';const meta=document.createElement('div');meta.className='lesson-video-meta';const label=document.createElement('span');label.textContent=ko()?'무료 샘플 레슨':'Free Sample Lesson';const duration=document.createElement('span');duration.className='lesson-video-duration';const clock=document.createElement('img');clock.src='/assets/site/5-1265-f1f6a.svg';clock.alt='';duration.append(clock,document.createTextNode(v.duration));meta.append(label,duration);const h=document.createElement('h3'),title=link.cloneNode(false);title.className='';title.textContent=ko()?v.koreanTitle:v.englishTitle;h.append(title);heading.append(meta,h);const bottom=document.createElement('div');bottom.className='lesson-video-bottom';const avatars=document.createElement('div');avatars.className='lesson-video-avatars';(v.avatars||[]).forEach(a=>{const img=document.createElement('img');img.src=a.url;img.alt=a.name||'';img.loading='lazy';avatars.append(img)});const comments=link.cloneNode(false);comments.className='lesson-comment-link';comments.href+= '&t='+v.seconds+'s';comments.textContent='+';comments.setAttribute('aria-label',ko()?'YouTube에서 보기':'Watch on YouTube');avatars.append(comments);const watch=link.cloneNode(false);watch.className='lesson-video-watch';watch.textContent=ko()?'YouTube에서 보기 →':'Watch on YouTube →';bottom.append(avatars,watch);content.append(heading,bottom);article.append(link,content);list.append(article)})}
tabs.forEach((tab,i)=>{tab.addEventListener('click',()=>{category=i;renderVideos()});tab.addEventListener('keydown',e=>{let next=i;if(['ArrowRight','ArrowDown'].includes(e.key))next=(i+1)%tabs.length;else if(['ArrowLeft','ArrowUp'].includes(e.key))next=(i+tabs.length-1)%tabs.length;else if(e.key==='Home')next=0;else if(e.key==='End')next=tabs.length-1;else return;e.preventDefault();category=next;renderVideos();tabs[next].focus()})});renderVideos();document.addEventListener('musium-language',renderVideos);
const film=document.querySelector('#performance-film'),play=document.querySelector('.play-performance'),poster=document.querySelector('[data-node-id="5:1432"]');play.addEventListener('click',async()=>{film.style.display='block';try{await film.play();play.hidden=true;poster.hidden=true}catch{film.controls=true;play.hidden=true;poster.hidden=true}});film.addEventListener('play',()=>{play.hidden=true;poster.hidden=true});film.addEventListener('ended',()=>{play.hidden=false;poster.hidden=false;film.style.display='none'});
const dialog=document.querySelector('#consult-dialog'),form=document.querySelector('#consult-form'),body=document.querySelector('#consult-body'),success=document.querySelector('#consult-success'),error=document.querySelector('#form-error'),student=document.querySelector('#consult-student'),age=document.querySelector('#consult-age'),ageField=document.querySelector('#consult-age-field');let opener,pending=false;
const placeholderEnglish=Object.fromEntries([...form.querySelectorAll('[data-placeholder]')].map(el=>[el.dataset.placeholder,el.placeholder]));
const placeholderKorean={'consult-name':'성인 또는 부모님 / 보호자 성함','consult-age':'나이만 입력해 주세요 (생년월일 불필요)','consult-availability':'예: 평일 오후 4시 이후 또는 토요일 오전','consult-goals':'목표, 궁금한 점, 선생님께 전하고 싶은 이야기를 적어 주세요…'};
function localizeForm(){form.querySelectorAll('[data-placeholder]').forEach(el=>el.placeholder=(ko()?placeholderKorean:placeholderEnglish)[el.dataset.placeholder]);dialog.querySelector('.dialog-close').ariaLabel=ko()?'상담 창 닫기':'Close consultation';form.querySelector('.sending-label').textContent=ko()?'보내는 중…':'Sending…'}
localizeForm();document.addEventListener('musium-language',localizeForm);
function updateAge(){age.disabled=student.value!=='Child or teen';ageField.hidden=student.value==='Adult';if(age.disabled)age.value=''}
student.addEventListener('change',updateAge);updateAge();
document.querySelectorAll('[data-consult]').forEach(b=>b.addEventListener('click',()=>{opener=b;dialog.showModal();dialog.scrollTop=0}));
function close(){if(!pending)dialog.close()}
dialog.querySelector('.dialog-close').addEventListener('click',close);dialog.querySelector('[data-close]').addEventListener('click',close);
dialog.addEventListener('cancel',e=>{if(pending)e.preventDefault()});
dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)close()}});
dialog.addEventListener('close',()=>{if(!pending&&!success.hidden){body.hidden=false;success.hidden=true;dialog.classList.remove('is-success');dialog.setAttribute('aria-labelledby','consult-title')}opener?.focus()});
function clearErrors(){error.hidden=true;form.querySelectorAll('.field-error').forEach(el=>el.remove());form.querySelectorAll('[aria-invalid]').forEach(el=>{el.removeAttribute('aria-invalid');el.removeAttribute('aria-describedby')})}
function showFieldError(field,message){field.setAttribute('aria-invalid','true');let el=document.createElement('span');el.className='field-error';el.id=field.id+'-error';el.textContent=message;field.setAttribute('aria-describedby',el.id);field.closest('label').append(el)}
form.addEventListener('input',e=>{const field=e.target;if(field.hasAttribute('aria-invalid')){field.removeAttribute('aria-invalid');field.removeAttribute('aria-describedby');field.closest('label')?.querySelector('.field-error')?.remove()}});
form.noValidate=true;
form.addEventListener('submit',async e=>{
 e.preventDefault();if(pending)return;clearErrors();
 const invalid=[...form.elements].filter(f=>f.willValidate&&!f.checkValidity());
 if(invalid.length){invalid.forEach(f=>showFieldError(f,ko()?(f.validity.valueMissing?'필수 항목을 입력하거나 선택해 주세요.':f.type==='email'?'올바른 이메일 주소를 입력해 주세요.':'입력값을 확인해 주세요.'):f.validationMessage));const labels=invalid.map(f=>f.closest('label').querySelector('[data-copy]').textContent.replace(/\s*\*\s*$/,'')).join(', ');error.textContent=(ko()?'다음 항목을 확인해 주세요: ':'Please check these fields: ')+labels;error.hidden=false;invalid[0].focus();invalid[0].scrollIntoView({block:'center',behavior:'instant'});return}
 const data=new FormData(form);
 const val=key=>String(data.get(key)||'').trim();
 const payload=new URLSearchParams({name:val('name'),email:val('email'),Student:val('student'),'Student age':val('student')==='Adult'?'Adult':val('age')||'Not provided','Piano experience':val('experience'),'Lesson format':val('format'),'Availability (Chicago time)':val('availability')||'Not provided','Goals and questions':val('goals')||'Not provided',subject:'Musium — New Free Consultation Request',source:location.origin+location.pathname,_gotcha:''});
 const submit=form.querySelector('[type=submit]'),label=submit.querySelector('[data-copy]'),sending=submit.querySelector('.sending-label'),fields=form.querySelector('fieldset');
 pending=true;form.setAttribute('aria-busy','true');submit.disabled=true;fields.disabled=true;label.hidden=true;sending.hidden=false;
 const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),30000);
 try{
  const response=await fetch(form.getAttribute('action'),{method:'POST',headers:{Accept:'application/json'},body:payload,signal:controller.signal});
  const text=await response.text();let result;try{result=text?JSON.parse(text):{}}catch{throw new Error(ko()?'접수 확인 응답을 받지 못했습니다. 입력 내용은 보존되었습니다.':'We could not confirm your request. Your entries are still here.')}
  if(!response.ok||result.ok===false||result.errors?.length||result.error){
   const messages=(result.errors||[]).map(item=>item.message).filter(Boolean);if(result.error)messages.push(result.error);
   const map={email:'email',name:'name',Student:'student','Piano experience':'experience','Lesson format':'format'};
   (result.errors||[]).forEach(item=>{const field=form.elements.namedItem(map[item.field]||item.field);if(field?.closest('label'))showFieldError(field,item.message||'Please check this field.')});
   throw new Error(response.status===429?(ko()?'신청이 많아 잠시 후 다시 시도해 주세요.':'Too many requests. Please wait a moment and try again.'):messages.join(' ')||(ko()?`접수가 거절되었습니다 (오류 ${response.status}).`:`Your request was not accepted (error ${response.status}).`))
  }
  body.hidden=true;success.hidden=false;dialog.classList.add('is-success');const heading=success.querySelector('h2');heading.id='consult-success-title';dialog.setAttribute('aria-labelledby',heading.id);dialog.scrollTop=0;heading.tabIndex=-1;heading.focus();form.reset();updateAge();
 }catch(err){error.textContent=(err.name==='AbortError'?(ko()?'서버 응답 시간이 초과되었습니다. 입력 내용은 보존되었습니다.':'The server took too long to respond. Your entries are still here.'):err instanceof TypeError?(ko()?'서버에 연결하지 못했습니다. 인터넷 연결을 확인해 주세요.':'We could not connect to the server. Please check your internet connection.'):err.message)+' '+(ko()?'다시 시도하거나 pianomusium@gmail.com으로 문의해 주세요.':'Please try again or email pianomusium@gmail.com.');error.hidden=false;error.scrollIntoView({block:'nearest'})}
 finally{clearTimeout(timeout);pending=false;form.removeAttribute('aria-busy');submit.disabled=false;fields.disabled=false;label.hidden=false;sending.hidden=true;updateAge()}
});

})();
